order_system/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    
    

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

   
    url(r'^demo/', include('product_order.urls')),

    url(r'^service_order_demo/', include('service_order.urls')),

    
)

product_order/urls.py
from django.conf.urls import patterns, include, url

from product_order import views, data_views

urlpatterns = patterns('',

     url(r'^$', views.index),
     url(r'^order_state_machine/$', views.order_state_machine),
     url(r'^make_order/$', views.make_order),
     url(r'^make_order2/$', views.make_order2),
     url(r'^make_order3/$', views.make_order3),
     url(r'^create_order/$', views.create_order),
     url(r'^order_state_machine/data/role/(?P<role>[^/]+)/$', data_views.get_actions),
     url(r'^view_refund_sheet/$', views.view_refund_sheet),
     

)

order/models.py
#-*- coding: utf-8 -*

import sys
import time
import random
import hashlib
import copy

from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.conf import settings
from django.core.files.storage import FileSystemStorage    



import snapshot

OPERATOR_ROLE_CHOICES = (
        ('P', 'Platform'),('A', 'Admin'),('B', 'Buyer'),('S', 'Seller'),
    )

#TODO:better regex
#To support comma separated states. So far the maximum number of states supported is 5 comma separated states string
def state_machine_match_regex(st):
    return r'^\*$|^'+st+'$|^'+st+',|,'+st+'$|,'+st+',|^'+st+'$'






ORDER_STATE_CHOICES = (
        ('WP', _('Waiting for Payment')),('FP', _('Finished Payment')),('FS', _('Finished Shipping')), ('HS', _('Hold Shipping')), 
        ('ST', _('Successful Transatcion')), ('CT', _('Closed Transatcion')), 
        ('WA', _('Waiting for Accounting')), ('FA', _('Finished Accounting')),
    )

#state for Service_Order
# ORDER_STATE_CHOICES = (
#         ('WP', _('Waiting for Payment')),('FP', _('Finished Payment')),
#         ('ST', _('Successful Transatcion')), ('CT', _('Closed Transatcion')), 
#         #('WA', _('Waiting for Accounting')), ('FA', _('Finished Accounting')),
#     )



#'WSA' is added. The product design document will add this too.
# 'CSA' is added. Before return and after return of the item, the "force refund" action will cause different results for refund with return item 
REFUND_STATE_CHOICES = (
        ('WSR', _('Waiting For Seller Response')),('WSA', _('Waiting For Seller Response After Return')),('PPR', _('Platform Processing Refund')), ('SRR', _('Seller Rejected Refund')), 
        ('CSI', _('Customer Service Involved')), ('WBS', _('Waiting For Buyer Shipping Back')), #WBS only used for refund with return type of refund
        ('CSA', _('Customer Service Involved After Return')),
        ('PFR', _('Platform Finished Refund')), ('CCR', _('Clustomer Closed Refund')), ('PCR', _('Platform Closed Refund')),
    ) #if a refund is closed, the corresponding item cannot be requested refund again.
#TODO:change Finished Refund to Successful Refund


#state for SO_Refund_Sheet
# REFUND_STATE_CHOICES = (
#        ('PPR', _('Platform Processing Refund')),        
#        ('PFR', _('Platform Finished Refund')), 
#     )




class State_Machine(models.Model):
    operator_role = models.CharField(max_length=1, choices=OPERATOR_ROLE_CHOICES)
    action = models.CharField('action to do', max_length=256)  
    current_state = models.CharField(max_length=128) 
    next_state = models.CharField(max_length=3)
    post_action = models.CharField('action to do afterwards by the platform', max_length=64) 

    class Meta:
        abstract = True



    @classmethod
    def get_initial_state(cls):
        return ''


    @classmethod
    def get_next(cls, role, action, c_state):
        try:
            osm = cls.objects.get(operator_role=role, action=action, current_state__regex=state_machine_match_regex(c_state))
            return osm.next_state, osm.post_action
        except MultipleObjectsReturned, mor:
            #TODO:make a custom exception
            raise Exception('Multiple states returned!') 
        #TODO:
        except ObjectDoesNotExist, dne:
            return None, None    

    
    


    @classmethod
    def get_role_actions(cls, c_state):
        '''Get which roles can do what actions when the order is in a certain state
        '''      
        osms = cls.objects.filter(current_state__regex=state_machine_match_regex(c_state)).values_list('operator_role','action')   
        roles = list(set([osm[0] for osm in osms]))        
        role_actions = {}
        for r in roles:
            role_actions[r] = []
            for s in osms:
                if s[0]==r:
                    role_actions[r].append(s[1])
        return role_actions   


    


    #TODO:remove
    @classmethod
    def get_initials(cls):
        osms = cls.objects.filter(current_state=self.get_initial_state())   
        return osms   

   
    @classmethod
    def get_initial_role_actions(cls):
        ras = cls.get_role_actions(cls.get_initial_state())
        return ras      






#actually exactly the same as order state machine TODO:use abstract table
class Refund_State_Machine(State_Machine):
  
    class Meta:
        abstract = True



    @classmethod
    def get_initial_state(cls):
        return 'WSR'



def remove_no_display_actions(role_actions, no_display_actions):
    #need to be deep copy here. Otherwise it only copies the reference (to the list inside in this case)
    #modifying a list in one will also change the other
    ras = copy.deepcopy(role_actions) 
    for role in ras.keys():
        for action in ras[role]:
            if action in no_display_actions:
                role_actions[role].remove(action)
        if not role_actions[role]:
            role_actions.pop(role)
    return role_actions        

   
class Work_Flow(models.Model): 
    '''State machine controlled work flow
    '''  
    #id =  models.CharField(max_length=64, primary_key=True) 
    state = models.CharField(max_length=3)

    class Meta:
        abstract = True



    @classmethod
    def get_state_machine(cls): 
        pass 


    def get_role_actions(self):
        '''Get which roles can do what actions when the refund sheet is in a certain state
        '''             
        ras = self.__class__.get_state_machine().get_role_actions(self.state)    
        return self.remove_actions(ras)
        
    
    def remove_actions(self, ras):
        pass


    def goto_next(self, role, action, **kwargs):        
        next_state, post_action = self.__class__.get_state_machine().get_next(role, action, self.state)        
        if next_state:
            self.state = next_state
            self.save()
            if post_action:
                getattr(sys.modules[self.__class__.__module__], post_action)(self.id)
        self.common_post_action(role, action, **kwargs)    
        return next_state, post_action    
          

    def common_post_action(self, role, action, **kwargs):
        pass      
    
    def get_state_display(self):
        pass


class Order(Work_Flow):    
    buyer_id = models.CharField(max_length=10) #TODO:move to order center?
    #state = models.CharField(max_length=2, choices=ORDER_STATE_CHOICES, null=True) 
    

    def __unicode__(self):
        return unicode(self.id)


    #TODO: implement this by adding one extra parameter: order_type, so it is more convenient for usage
    @classmethod
    def create_order(cls, id=None, buyer_id='877673433', item_list=['92399069', '83768385'], **kwargs):     
        pass

  


    def get_state_display(self):
        return dict(ORDER_STATE_CHOICES).get(self.state)


    #calling order center using this order_system might want to hide WA and FA states, then they can use this mentod to display the state
    def get_custom_state_display(self):
        if self.state in ['WA', 'FA']:
            return _('Successful Transatcion') #testing translation TODO:
        elif self.state == 'HS':
            return _('Finished Payment')
        else:
            return self.get_state_display() 
            
    

    
    def get_order_type(self):    
        return 'order'

    #TODO:test
    #TODO: to be used in order center
    def get_items(self):
        """


        """
        pass
        # if self.get_order_type() == 'product':
        #     return self.product_order.order_item_rel_set.all()
        # else:#assume service
        #     return self.service_order.order_item_rel_set.all()    
               

 
 

class Refund_Sheet(Work_Flow):       
    #state = models.CharField(max_length=3, choices=REFUND_STATE_CHOICES, null=True)  
    #so far, read refund_fee from refund_log
    #refund_fee = models.DecimalField(null=True, max_digits=9, decimal_places=2, verbose_name='refund fee')     
  

    
    def get_refund_type(self):
        """
     

        """                    
        log.info('No refund type detected!')
        return 'order' 

    
    def get_pics(self):
        """get the first three pics of the refund_sheet if available


        """
        return self.refund_sheet_pic_set.all().order_by('-pk')[:3]
    

    def get_main_log(self):
        pass


    #TODO:get the order_item_rel so it is convenient to go back
    def get_item(self):
        pass

class Refund_Log(models.Model):
    action = models.CharField('action done', max_length=256)     
    memo = models.TextField(blank=True)
    operator = models.CharField(max_length=30)
    refund_fee = models.DecimalField(null=True, max_digits=9, decimal_places=2, verbose_name='refund fee') 
    init_time = models.DateTimeField('time created', auto_now_add=True)        






fs = FileSystemStorage(location=settings.MEDIA_ROOT)


def get_storage_loc(instance, filename):        
    return 'refund_pics/'+str(instance.refund_sheet.id)+'_'+str(time.time()).replace('.', '')
    

class Refund_Sheet_Pic(models.Model):
     refund_sheet = models.ForeignKey(Refund_Sheet)
     pic = models.ImageField(upload_to=get_storage_loc, blank=True, storage=fs, verbose_name=_('refund pictures'))
    



def save_snapshot(order_id, item_list, default_snapshot_class, **kwargs):
    ''' item_list accept two types of data, one is a list of str (commodity_id), 
        the other is a list of dict, which contains other fields of each item to 
        be saved in snapshot. For the first case, the other fieldnames need to be 
        obtained from kwargs, where you might use some method depending on the convention
        set up (for example, prefix each field with item1_ to denote that this field belongs
        to item1)
    '''
    item_class = kwargs.pop('item_class', '')
    if not item_class:
        item_class = eval(default_snapshot_class)
    else:

templates/product_order/create_order.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<body>


<form action="/demo/create_order/" method="post">{% csrf_token %}
	{% for item in items %}
		<input type="checkbox" name="item_id" value="{{item.commodity_id}}">{{item.title}}<br>
        <input type="hidden" name="item_name" value="{{item.title}}"/>
    {% endfor %}
    <input type="submit" value="{% trans "create order" %}">
</form>	


</body>
</html>	

templates/product_order/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<body>

View the demo of the state machine: <a href="order_state_machine/">state machine of order</a> <br/><br/>
View the demo of making an order: <a href="make_order/">Make order</a> <br/><br/>
View the complete demo of making an order, together with states of commodities: <a href="make_order2/">Make order</a> <br/><br/>
View a more complete demo of the order system: <a href="create_order/">Make order</a> <br/><br/>
</body>
</html>

templates/product_order/make_order.html
{% load i18n %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="/static/common/js/jquery-1.7.1.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(function(){
	$('.sel_cont').each(function(index){
			onChange($(this));
	})	
	function onChange(obj){
		obj.change(function(){
			//alert('called');
			var arr = getData(obj);
			//alert('selected:'+arr)
			$.get(
				setUrl(arr),
				function(data){
					if(data){
						
						if(obj.next('select').next('select').length){
								obj.next('select').next('select').html('<option value="0">Please pick</option>')
						}
						h = ''
						for (var i=0;i<data.length;i++){
                           h = h + '<option value="'+data[i]+'">'+data[i]+'</option>'
                        }
						obj.next('select').html(h);
						
						
					}	
				},
			'JSON')
		})		
	}
	function getData(obj){
		var aData = [];
		aData.push(obj.val());
		while(obj.prev('select').length){
			obj = obj.prev('select');
			aData.push(obj.val())
		}
		return aData;
	}
	function setUrl(arr){
		if(arr.length == 1){
			return 	'data/role/' + arr[0] + '/' +'?current_state={{current_state}}'
		}
		if(arr.length == 2){
			return 	'data/role/' + arr[0] + '/action/' + arr[1] + '/' +'?current_state={{current_state}}'
		}
	}
})
</script>
</head>
<body>

<b>Glossary</b>:<br/>
<div>{% trans 'roles' %}:   P=Platform, A=Admin, B=Buyer, S=Seller</div>
<div>{% trans 'order states' %}: WP='Waiting for Payment', FP='Finished Payment', FD='Finished Delivery',
        ST='Successful Transatcion', CT='Closed Transatcion'</div>

<br/><br/><br/><br/>
<b>{% trans 'order' %} {{order}} {% trans 'current state' %}:{{current_state}}</b>

<br/><br/><br/>
<div>
<b>buyer:</b><br/>

<ul>
{% for act in role_actions.B %}
<li>
    <a href="?order_id={{order.id}}&role=B&action={{act}}">{{act}}</a>
</li>     
{% endfor %}
</ul>
</div>

<br/><br/><br/>
<div>
<b>seller:</b><br/>

{% for act in role_actions.S %}
    <a href="?order_id={{order.id}}&role=S&action={{act}}">{{act}}</a>
{% endfor %}
</div>	

<br/><br/><br/>
<div>
<b>platform:</b><br/>
<ul>
{% for act in role_actions.P %}
   <li>
    <a href="?order_id={{order.id}}&role=P&action={{act}}">{{act}}</a>
   </li> 
{% endfor %}
</ul>
</div>	

<a href="/demo/make_order/">{% trans 'Back to the start' %}</a><br/>
<a href="/demo/">back to index</a>

</body>
</html>

templates/product_order/make_order2.html
{% load i18n %}
{% load extra %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<body>

<b>Glossary</b>:<br/>
<div>{% trans 'roles' %}:   P=Platform, B=Buyer, S=Seller</div>
<div>{% trans 'order states' %}: WP='Waiting for Payment', FP='Finished Payment', FS='Finished Shipping',
        ST='Successful Transaction', CT='Closed Transaction', WA='Waiting for Accounting', FA='Finished Accounting', HS='Hold Shipping' ({% trans 'The state HS will not be displayed at the ecommerce site. It is only to be viewed by backend tech people.' %})</div>
<div>{% trans 'order items states' %}: FP='Finished Payment', WR='Waiting for Refund', FR='Finished Refund', CR='Closed Refund'</div>

<div style="font-size:small;">
{% trans 'Notice' %}：{% trans 'There is no display of refund sheet states. But actions made have taken into account the states of refund sheet. If necessary, refund sheet states can be displayed here as well.' %}
</div>

<br/><br/>

<a href="#notice">{% trans 'About this demo' %}</a>



<br/><br/><br/><br/>
<b>{% trans 'order' %} {{order}} {% trans 'current state' %}:{{order.state}} ({{ order.get_state_display }})</b> <a href="?order_id={{order}}&refresh=y">{% trans 'refresh' %}</a>    

<br/><br/>

<br/><br/>
<div style="border:dotted;">
<b>buyer:</b><br/>

<ul>{% trans 'Actions currently available  on the order' %}:
{% for act in order.get_role_actions.B %}
<li>
    <a href="?order_id={{order}}&role=B&action={{act}}">{% trans act %}</a>
</li>     
{% endfor %}
</ul>

<br/>
<ul>{% trans 'Items in the order' %}({% trans 'item id, item name, item state, actions currently available  on the item' %}):
{% for item in order.order_item_rel_set.all  %}
<li>
    {{item.item_id}} &nbsp;&nbsp;{{item.get_item.name}}&nbsp;&nbsp; state:{{item.state}} ({{ item.get_state_display }}) &nbsp;&nbsp;   
    {%with item.get_role_actions as item_ras %} 
    {% for key in item_ras.keys %}
        {%if key == 'B' %}
            {%for a in item_ras.B %}
                <a href="?order_id={{order}}&item_id={{item.item_id}}&role=B&item_action={{a}}">{% trans a %}</a>&nbsp;&nbsp;
            {% endfor %}    
        {% endif %}        
    {% endfor %} 
    {% endwith %}   
</li>     
{% endfor %}
</ul>


</div>

<br/><br/><br/>
<div style="border:dotted;">
<b>seller:</b><br/>
<ul>{% trans 'Actions currently available  on the order' %}:
{% for act in order.get_role_actions.S %}
<li>
    <a href="?order_id={{order.id}}&role=S&action={{act}}">{% trans act %}</a>
</li>     
{% endfor %}
</ul>

<br/>
<ul>{% trans 'Items in the order' %}({% trans 'item id, item name, item state, actions currently available  on the item' %}):
{% for item in order.order_item_rel_set.all %}
<li>
    {{item.item_id}} &nbsp;&nbsp;{{item.get_item.name}}&nbsp;&nbsp; state:{{item.state}} ({{ item.get_state_display }})&nbsp;&nbsp;   
    {%with item.get_role_actions as item_ras %}
    {% for key in item_ras.keys %}
        {%if key == 'S' %}
            {%for a in item_ras.S %}
                <a href="?order_id={{order.id}}&item_id={{item.item_id}}&role=S&item_action={{a}}">{% trans a %}</a>&nbsp;&nbsp;
            {% endfor %}    
        {% endif %}        
    {% endfor %} 
    {% endwith %}   
</li>     
{% endfor %}
</ul>

</div>	



<br/><br/><br/>
<div style="border:dotted;">
<b>platform:</b><br/>
<ul>{% trans 'Actions currently available  on the order' %}:
{% for act in order.get_role_actions.P %}
   <li>
    <a href="?order_id={{order.id}}&role=P&action={{act}}">{% trans act %}</a>
   </li> 
{% endfor %}
</ul>

<br/>
<ul>{% trans 'Items in the order' %}({% trans 'item id, item name, item state, actions currently available  on the item' %}):
{% for item in order.order_item_rel_set.all  %}
<li>
    {{item.item_id}} &nbsp;&nbsp;{{item.get_item.name}}&nbsp;&nbsp; state:{{item.state}}({{ item.get_state_display }}) &nbsp;&nbsp;   
    {%with item.get_role_actions as item_ras %}
    {% for key in item_ras.keys %}
        {%if key == 'P' %}
            {%for a in item_ras.P %}
                <a href="?order_id={{order.id}}&item_id={{item.item_id}}&role=P&item_action={{a}}">{% trans a %}</a>&nbsp;&nbsp;
            {% endfor %}    
        {% endif %}        
    {% endfor %} 
    {% endwith %}   
</li>     
{% endfor %}
</ul>

{% trans 'Please be aware that the timed tasks can be viewed by the monitoring web console, ' %}<a href="{% settings_value "CELERY_MONITOR_SITE" %}" target="top">{% trans 'timed tasks monitoring' %}</a>
<br/><br/>
</div>	

<br/><br/><br/><br/>
<a href="/demo/make_order2/">{% trans 'Back to the start' %}</a><br/>
<a href="/demo/">back to index</a>


<br/><br/><br/><br/>
<div style="font-size:small;">
<a id="notice">{% trans 'Notice' %}说明</a>：{% trans 'This demo is a demo for the ordering system, which can be used as middleware for various ordering centers in the ecommerce platform. It demonstrates the states that the order needs to go through, and the actions from each role (buyer, seller, platform) that can be applied to the order when in a certain state, the states of the order and its items after the action, and actions available next. This demo put these roles and actions on the same page demonstrate the workflow of order system. This demo is for product order. In addition, we also have' %}<a href="/service_order_demo/">{% trans 'service order demo' %}</a>。


<ul>{% trans 'The types of actions of the platform' %}：
<li>
1.{% trans 'The action triggered by the state change. These actions are written in the database table of the state machines. These actions are executed immediately' %}；
</li>
<li>
2.{% trans 'Timed tasks, such as whether there is payment within 24 hours, whether seller has responded to the refund request within 72 hours' %}；
</li>
<li>
3.{% trans 'Inputs from other systems, such as from payment system notifying payment is successfully finished' %}；
</li>
<li>
4.{% trans 'Manually triggered action by admins. For example, customer representatives can force a refund. For now, we treat this type of action as a platform action as well.' %}
</li>
</ul>

{% trans 'Please be aware that the timed tasks can be viewed by the monitoring web console, ' %}<a href="{% settings_value "CELERY_MONITOR_SITE" %}" target="top">{% trans 'timed tasks monitoring' %}</a>

</div>

</body>
</html>

templates/product_order/make_payment.html
{{order}}

templates/product_order/order_state_machine.html
{% load i18n %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="/static/common/js/jquery-1.7.1.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(function(){
	$('.sel_cont').each(function(index){
			onChange($(this));
	})	
	function onChange(obj){
		obj.change(function(){
			//alert('called');
			var arr = getData(obj);
			//alert('selected:'+arr)
			$.get(
				setUrl(arr),
				function(data){
					if(data){
						
						if(obj.next('select').next('select').length){
								obj.next('select').next('select').html('<option value="0">请选择</option>')
						}
						h = ''
						for (var i=0;i<data.length;i++){
                           h = h + '<option value="'+data[i]+'">'+data[i]+'</option>'
                        }
						obj.next('select').html(h);
						
						
					}	
				},
			'JSON')
		})		
	}
	function getData(obj){
		var aData = [];
		aData.push(obj.val());
		while(obj.prev('select').length){
			obj = obj.prev('select');
			aData.push(obj.val())
		}
		return aData;
	}
	function setUrl(arr){
		if(arr.length == 1){
			return 	'data/role/' + arr[0] + '/' +'?current_state={{current_state}}'
		}
		if(arr.length == 2){
			return 	'data/role/' + arr[0] + '/action/' + arr[1] + '/' +'?current_state={{current_state}}'
		}
	}
})
</script>
</head>
<body>

<b>Glossary</b>:<br/>
<div>{% trans 'roles' %}:   P=Platform,B=Buyer, S=Seller</div>
<div>{% trans 'order states' %}: WP='Waiting for Payment', FP='Finished Payment', FD='Finished Delivery',
        ST='Successful Transatcion', CT='Closed Transatcion', WA='Waiting for Accounting', FA='Finished Accounting'</div>

<br/><br/><br/><br/>
<b>{% trans 'Order state machine current state' %} :{{current_state}}</b>

<form action=''>{% trans 'roles' %}:
   <select name="role" class="sel_cont">
     	<option value="0" >{% trans 'Please pick' %}</option>
	    {% for role in role_actions.keys %}
		<option value="{{role}}" >{{role}}</option>
		{% endfor %}    
   </select>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	
   {% trans 'Operation/Trigger' %}:
   <select name="action">
		<option value="0" >{% trans 'Please pick' %}</option>		
   </select>
   <input type="hidden" name="current_state" value="{{current_state}}"/>
   <input type="submit" value="{% trans 'Execute' %}"/>
</form>



<br/><br/>
<a href="/demo/order_state_machine/">{% trans 'Back to the start' %}</a><br/>
<a href="/demo/">back to index</a>
</body>
</html>

templates/product_order/view_refund_sheet.html
{% load i18n %}


<style>
td{
  border:1px solid;  
}
</style>


退款状态：{{refund_sheet.state}} ({{refund_sheet.get_state_display}})<br/>

退款单号:{{refund_sheet.id}}<br/>
退款类型：{{refund_sheet.refund_type}}<br/>
退款金额：{{refund_sheet.refund_fee}}<br/>
申请退款时间：{{refund_sheet.init_time}}<br/>
退款理由：{{refund_sheet.reason}}<br/>
退款说明：{{refund_sheet.memo}}
<br/><br/><br/>

<b>退款记录：</b><br/>
<table>
<tr>	
{% for rl in refund_sheet.refund_log_set.all %}
<td>
 操作者: {{rl.operator}}<br/>
</td>
<td> 
 操作动作：{{rl.action}}<br/>
 生成时间：{{rl.init_time}}<br/>
 退款类型：{{rl.refund_type}}<br/>
 退款金额：{{rl.refund_fee}}元<br/>
 退款理由：{{rl.reason}}<br/>
 退款说明：{{rl.memo}}
</td> 
</tr>

{% endfor %}
</table>